### ISSUE TITLE
Visualization of angle optimization

### ISSUE THREAD

**Issue by mishkat1096** [Naruki-Ichihara/morphogenesis#8]
Hi, thanks for the great tool.
I was wondering how to visualize the angles after optimizing.
The files are written in `.pvd` doesn't show appropriate angles in `paraview`.
Is any other visualization that can be helpful ?

Thanks

**Comment by Naruki-Ichihara** [comment]
Sorry for the very late reply. One of the options for angle visualizing is using a vector field. 
If the optimized radian angles are stored in function `theta` defined in the CG space, we can project them onto the directional vectors using the following code.
```python
vector = project((cos(theta), sin(theta)), VectorFunctionSpace(mesh, 'CG', 1))
vector.rename('director', 'director')
```
then, we can save it as the `.xdmf` or `.pvd` as follows.
```python
file = File('<file path>/angle.pvd')
file << vector
```
